---
url_jdbc_base: 'jdbc:mysql://{{ db_server }}:{{ db_port }}/'
url_jdbc_suffix: '&useUnicode=true&characterEncoding=UTF-8'
archivesspace_version: 'v2.0.1'
db_host: '{{ maria_db_cluster_host | default("localhost") }}'
archivesspace_db_password: '{{ vault_archivesspace_db_password }}'
