passenger_server_name: "figgy-staging.princeton.edu"
passenger_app_root: "/opt/figgy/current/public" 
passenger_app_env: "staging"
rails_app_name: "figgy"
rails_app_directory: "figgy"
rails_app_symlinks: []
rails_app_dependencies:
  - libpq-dev
  - cifs-utils
  - nfs-common
  - libopenjp2-7-dev
  - libmagickwand-dev
  - imagemagick
  - pkg-config
figgy_db_name: 'figgy_staging'
figgy_db_user: '{{vault_figgy_db_user}}'
figgy_db_password: '{{vault_figgy_db_password}}'
rails_app_env: "staging"
solr_remove_cruft: true
figgy_solr_name: figgy-staging
solr_cores:
  - '{{figgy_solr_name}}'
solr_version: "6.2.1"
application_host: '{{passenger_server_name}}'
application_host_protocol: 'https'
rails_app_vars:
  - name: SECRET_KEY_BASE
    value: '{{vault_figgy_secret_key}}'
  - name: FIGGY_DB
    value: '{{figgy_db_name}}'
  - name: FIGGY_DB_USERNAME
    value: '{{figgy_db_user}}'
  - name: FIGGY_DB_PASSWORD
    value: '{{figgy_db_password}}'
  - name: FIGGY_DB_HOST
    value: '127.0.0.1'
  - name: APPLICATION_HOST
    value: '{{application_host}}'
  - name: APPLICATION_HOST_PROTOCOL
    value: '{{application_host_protocol}}'
  - name: SOLR_URL
    value: 'http://127.0.0.1:{{solr_port}}/solr/{{figgy_solr_name}}'
  - name: CANTALOUPE_URL
    value: 'http://{{passenger_server_name}}:8182/iiif/2/'
sidekiq_worker_name: figgy-workers
cantaloupe_user: '{{deploy_user}}'
cantaloupe_group: '{{deploy_user}}'
cantaloupe_FilesystemResolver_BasicLookupStrategy_path_prefix: /opt/repository/derivatives/
cantaloupe_cache_source: FilesystemCache
cantaloupe_cache_derivative: FilesystemCache
cantaloupe_create_FilesystemCache_dir: yes
cantaloupe_version: 3.3.2
cantaloupe_KakaduProcessor_path_to_binaries: /opt/kakadu
cantaloupe_log_application_level: all
