---
buffer_memory: '{{ quarter_system_memory | default("128MB") }}'
cache_size: '{{ two_third_system_memory | default("4GB") }}'
min_wal: '{{ one_gig | default("80MB") }}'
max_wal: '{{ two_gig | default("1GB") }}'
