---
- hosts: archivesspace
  remote_user: pulsys
  become: true
  vars_files:
    - site_vars.yml
    - group_vars/archivesspace.yml
  roles:
    - role: pulibrary.deploy-user
    - role: pulibrary.oracle.java8
    - {role: pulibrary.mariadb, when: db_host == 'localhost'}
    - role: pulibrary.archivesspace
