---
- hosts: figgy
  remote_user: pulsys
  become: true
  vars_files:
    - site_vars.yml
  roles:
    - role: pulibrary.ruby
    - role: pulibrary.deploy-user
    - role: pulibrary.passenger
    - role: pulibrary.redis
    - role: pulibrary.postgresql
    - role: pulibrary.nodejs
    - role: pulibrary.kakadu
    - role: pulibrary.oracle.java8
    - role: pulibrary.extra_path
    - role: pulibrary.rails-app
    - role: pulibrary.solr
    - role: pulibrary.cantaloupe
    - role: pulibrary.sidekiq_worker
    - role: pulibrary.figgy
