---
- hosts: plum
  remote_user: pulsys
  become: true
  vars_files:
    - site_vars.yml
  vars:
    samba_users:
      - name: pulsys
        password: {{samba_pulsys_password}}
    samba_shares:
      - name: plum_geo_data
        group: sambashare
        write_list: +sambashare
  roles:
    - role: pulibrary.tomcat8
    - role: pulibrary.deploy-user
    - role: pulibrary.postgresql
    - role: pulibrary.samba
    - role: pulibrary.geoserver
