---
- hosts: libwwwstage
  remote_user: pulsys
  become: true
  vars_files:
    - site_vars.yml
    - group_vars/drupal/drupal.yml
    - group_vars/drupal/vault.yml
    - group_vars/libwww/libwww.yml
    - group_vars/libwww/vault.yml
  roles:
    - role: pulibrary.deploy-user
    - role: pulibrary.apache2
    - role: pulibrary.php
    - {role: pulibrary.mariadb, when: db_host == 'localhost'}
    - role: pulibrary.composer
    - role: pulibrary.drush
    - role: pulibrary.nodejs
    - role: pulibrary.oracle.java8
    - role: pulibrary.solr
    - role: pulibrary.redis
    - role: pulibrary.drupal
    - role: pulibrary.libwww
