---
- hosts: plum
  remote_user: systems
  become: true
  tasks:
    - name: Install list of packages
      apt: name={{item}} state=installed
      with_items:
        - nodejs
        - libpq-dev
        - curl
        - tesseract-ocr
        - tesseract-ocr-*
  roles:
    - role: git
    - role: ruby
    - role: redis
    - role: fits
    - role: ansiblebit.oracle-java
    - role: pulibrary.kakadu
    - role: pulibrary.deploy-user
    - role: pulibrary.extra_path
    - role: pulibrary.plum
- hosts: plum-workers
  remote_user: systems
  become: true
  roles:
    - role: pulibrary.plum_worker
- hosts: plum-derivative-workers
  remote_user: systems
  become: true
  roles:
    - { role: pulibrary.plum_worker, plum_worker_name: "plum-derivative", plum_worker_threads: 5, plum_worker_queues: ['default']}
- hosts: plum-derivative-xenial-workers
  remote_user: systems
  become: true
  roles:
    - role: pulibrary.plum_worker_xenial
