---
- hosts: plum
  remote_user: pulsys
  become: true
  vars_files:
    - site_vars.yml
  roles:
    - role: pulibrary.ruby
    - role: pulibrary.nodejs
    - role: pulibrary.redis
    - role: pulibrary.fits
    - role: pulibrary.oracle.java8
    - role: pulibrary.kakadu
    - role: pulibrary.deploy-user
    - role: pulibrary.extra_path
    - role: pulibrary.plum
- hosts: plum-workers
  remote_user: pulsys
  become: true
  roles:
    - role: pulibrary.plum_worker_xenial
- hosts: plum-derivative-workers
  remote_user: pulsys
  become: true
  roles:
    - { role: pulibrary.plum_worker_xenial, plum_worker_name: "plum-derivatives", plum_worker_threads: 5, plum_worker_queues: ['default', 'lowest']}
