---
- name: provision a vagrant box to mimic a production environment as closely as possible.
  hosts: vagrant
  #user: vagrant
  remote_user: pulsys
  #gather_facts: true
  vars:
  become: true
  vars_files:
    - site_vars.yml

  roles:
    - role: pulibrary.nodejs
    - role: pulibrary.oracle.java8
    - role: pulibrary.ruby
    - role: pulibrary.redis
    - role: pulibrary.fits
    - role: pulibrary.oracle.java8
    - role: pulibrary.kakadu
    - role: pulibrary.deploy-user
    - role: pulibrary.extra_path
    - role: pulibrary.plum
    - role: pulibrary.plum_worker_xenial
    - { role: pulibrary.plum_worker_xenial, plum_worker_name: "plum-derivative", plum_worker_threads: 5, plum_worker_queues: ['default']}
