---
- name: provision a vagrant box to mimic a production environment as closely as possible.
  hosts: vagrant
  #user: vagrant
  remote_user: vagrant
  #gather_facts: true
  vars:
  become: true
  vars_files:
    - site_vars.yml
  tasks:
    - name: Install list of packages
      apt: name={{item}} state=installed
      with_items:
        - nodejs
        - libpq-dev
        - curl
        - tesseract-ocr
        - tesseract-ocr-*
  roles:
    - role: pulibrary.oracle.java8
    - role: pulibrary.ruby
    - role: pulibrary.redis
    - role: pulibrary.fits
    - role: pulibrary.oracle.java8
    - role: pulibrary.kakadu
    - role: pulibrary.deploy-user
    - role: pulibrary.extra_path
    - role: pulibrary.plum
    - role: pulibrary.plum_worker
