---
# defaults file for pulibrary.plum
plum_directory: 'rails_app'
plum_derivatives_dir: '/mnt/libimages1/data/jp2s/plum_prod'
plum_uploads_dir: '/mnt/libimages1/data/tmp'
plum_environment: 'production'
