---
archivesspace_db_user: '{{ archivesspace_user | default("deploy") }}'
db_server: '{{ db_host }}'
archivesspace_db_name: 'archivesspace'
db_password: '{{ archivesspace_db_password }}'
db_port: 3306
