---
- name: install fits dependencies
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: "{{ apt_cache_timeout }}"
    update_cache: yes
  with_items:
    - unzip

- name: copy cached fits
  copy:
    src: "{{ local_files_dir }}/fits-{{ fits_version }}.zip"
    dest: /tmp/fits-{{ fits_version }}.zip
    register: cached_fits
    ignore_errors: True

- name: download fits
  get_url:
    url: "{{ fits_download_url }}/fits-{{ fits_version }}.zip"
    dest: /tmp/fits-{{ fits_version }}.zip
    timeout: 100
    owner: root
    group: root
    mode: 0444
  when: cached_fits|failed

- name: cache fits for future use
  fetch:
    src: /tmp/fits-"{{ fits_version }}".zip
    dest: "{{ local_files_dir }}/"
    flat: True
  when: ansible_virtualization_type == 'virtualbox'

- name: unarchive fits
  unarchive:
    src: /tmp/fits-{{ fits_version }}.zip
    dest: /opt copy=no creates=/opt/fits-{{ fits_version }}/fits.sh

- name: make fits directory accessible
  file:
    path: /opt/fits-{{ fits_version }}
    mode: a+x

- name: create sane scripting symbolic link
  file:
    src: /opt/fits-{{ fits_version }}
    dest: /opt/fits state=link

- name: make fits.sh executable
  file:
    path: /opt/fits-{{ fits_version }}/fits.sh
    mode: a+x
