---
- name: enable mysql pdo extension
  apt:
    name: ["php7.2-gd", "php7.2-mysql", "php7.2-mbstring", "php7.2-curl"]
    state: present
    update_cache: true
  when: ansible_distribution_release == "xenial"
  notify: restart apache
