---
- name: Create shared mount directories
  file:
    path: '/mnt/{{ item }}'
    state: directory
  with_items:
    - '{{ drupal_docroot }}'
  tags: ['never', 'notlocal']

- name: install mysql php driver
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - libapache2-mod-php7.2
    - php7.2-gd
    - php7.2-mysql

- name: install imagemagick
  apt:
    name: '{{ item }}'
    state: present
    with_items:
      - imagemagick

- name: Check to see if app root directory exists.
  stat:
    path: '{{ drupal_docroot }}'
  register: app_root_directory

- name: Creates app directory
  file:
    path: '{{ drupal_docroot }}'
    state: directory
    owner: 'pulsys'
    group: 'pulsys'
    mode: 0750
  become: true
  when: app_root_directory.stat.exists == false
  tags: ['never', 'vagrant']

- name: Creates fileshare directory
  file:
    src: '/mnt/{{ drupal_docroot }}'
    dest: '{{ drupal_docroot }}/sites/default/files'
    state: link
    owner: 'pulsys'
    group: 'pulsys'
    mode: 0750
  become: true
  tags: ['never', 'notlocal']

- name: clone the drupal repo
  git:
    repo: '{{ drupal_git_repo }}'
    version: '{{ drupal_version_branch }}'
    dest: '{{ drupal_docroot }}'
    accept_hostkey: 'yes'
    clone: 'yes'
    update: 'yes'
  become: 'pulsys'

- name: grant permissions on deploy user
  file:
    path: '{{ drupal_docroot }}'
    state: directory
    owner: deploy
    group: www-data
    recurse: 'yes'

- name: grant permissions on drupal files root
  file:
    path: '{{ drupal_docroot }}/sites/default/files'
    state: directory
    owner: deploy
    group: www-data
    recurse: 'yes'
    mode: 0770

- name: create composer directory
  file:
    path: '{{ drush_path }}/vendor'
    state: directory
    owner: pulsys
    group: pulsys
  become: 'no'
  become_user: pulsys
  when: drupal_major_version == 8

- name: create vendor directory
  file:
    path: '{{ drupal_docroot }}/vendor'
    state: directory
    owner: pulsys
    group: pulsys
  when: drupal_major_version == 8

- name: Drupal | Run composer if we are running D8
  composer:
    command: require
    working_dir: '{{ drush_path }}' # need to make a better decision for this
  become: 'no'
  become_user: pulsys
  when: drupal_major_version == 8

- name: Drupal | Run composer if we are running D8
  composer:
    command: install
    working_dir: '{{ drupal_docroot }}' # need to make a better decision for this
  become: 'no'
  become_user: pulsys
  when: drupal_major_version == 8

- name: Drupal | Check if site is already installed
  command: >
    drush status --root={{ drupal_docroot }}
  register: drush_status

- name: Drupal | Give appropriate permissions for files directory
  file:
    dest: '{{ drupal_docroot }}/sites/default/files'
    recurse: 'yes'
    mode: a+w
  when: not drush_status.stdout | search("Drupal bootstrap\s+:\s+Successful")

- include: mysql_setup.yml
  when: db_host == 'localhost'

- name: Drupal | Drush site install if not already installed
  command: >
    drush site-install standard -y
    --root={{ drupal_docroot }}
    --site-name={{ drupal_site_name }}
    --account-name={{ drupal_account_name }}
    --account-pass={{ drupal_account_pass }}
    --db-url=mysql://{{ drupal_db.user }}:{{ drupal_db.password }}@{{ db_host }}/{{ drupal_db.name }}
  args:
    chdir: "{{ drupal_docroot }}"
  when: not drush_status.stdout | search("Drupal bootstrap\s+:\s+Successful")
  become: 'yes'
  notify: 'restart apache'

- name: install modules with drush
  command: >
    drush pm-enable -y search_api_solr
    --root={{ drupal_docroot }}
