 version: 2.1
 jobs:
   test_roles:
     working_directory: ~/princeton_ansible
     docker:
       - image: quay.io/ansible/molecule:2.22rc3
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: Run molecule test for an Ansible role
           command: |
             for $PULIBRARY_ROLE in `find . -type d -regex '.*/roles/pulibrary.*/molecule/.*' | awk 'BEGIN { FS="/"; } { print $3 }' | uniq`
             do
               cd roles/$PULIBRARY_ROLE/
               molecule test
               cd ../..
             done

 workflows:
   ci:
     jobs:
       - test_roles:
           name: "test_roles"
