---
version: 2
jobs:
  build:
    working_directory: ~/princeton_ansible
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
      - checkout
      - persist_to_workspace:
          root: '~/princeton_ansible'
          paths: '*'
  ubuntu1604:
    working_directory: ~/princeton_ansible
    machine:
      enabled: true
      docker_layer_caching: true
    environment:
      ROLE_NAME: pulibrary.apache2
      MOLECULE_DISTRO: ubuntu1604
      PYTHON_VERSION: 3.7.2
    steps:
      - attach_workspace:
          at: '~/princeton_ansible'
      - run:
          name: Update apt repositories
          command: sudo apt-get -qq update
      - run:
          name: Install the deps for building Python
          command: sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev
      - run:
          name: Upgrade pyenv
          command: cd $(pyenv root) && git pull && cd -
      - run:
          name: Install the Python version
          command: pyenv install $PYTHON_VERSION
      - run:
          name: Set the desired Python version as the desired Python version
          command: pyenv global $PYTHON_VERSION
      - run:
          name: Install module requirements
          command: pip install -r requirements.txt
      - run:
          name: Run the default Molecule scenario
          command: molecule test
  ubuntu1804:
    working_directory: ~/princeton_ansible
    machine:
      enabled: true
      docker_layer_caching: true
    environment:
      ROLE_NAME: pulibrary.apache2
      MOLECULE_DISTRO: ubuntu1804
      PYTHON_VERSION: 3.7.2
    steps:
      - attach_workspace:
          at: '~/princeton_ansible'
      - run:
          name: Update apt repositories
          command: sudo apt-get -qq update
      - run:
          name: Install the deps for building Python
          command: sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev
      - run:
          name: Upgrade pyenv
          command: cd $(pyenv root) && git pull && cd -
      - run:
          name: Install the Python version
          command: pyenv install $PYTHON_VERSION
      - run:
          name: Set the desired Python version as the desired Python version
          command: pyenv global $PYTHON_VERSION
      - run:
          name: Install module requirements
          command: pip install -r requirements.txt
      - run:
          name: Run the default Molecule scenario
          command: molecule test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - ubuntu1604:
          requires:
            - build
      - ubuntu1804:
          requires:
            - build
