 version: 2.1
 jobs:
   test_roles:
     working_directory: ~/princeton_ansible
     docker:
       - image: quay.io/ansible/molecule:2.22rc3
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: Run molecule test for an Ansible role
           command: |
             python ./test.py

 workflows:
   ci:
     jobs:
       - test_roles:
           name: "test_roles"
