---
- name: Create snapshot systemd script
  template:
    src: consul_systemd_snapshot.service.j2
    dest: /lib/systemd/system/consul_snapshot.service
    owner: root
    group: root
    mode: 0644
  register: systemd_unit
  notify: start snapshot
  when:
    - consul_snapshot | bool

- name: Create snapshot agent config
  template:
    src: consul_snapshot.json.j2
    dest: "{{ consul_config_path }}/consul_snapshot.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644
  notify: start snapshot
  when:
    - consul_snapshot | bool

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: systemd_unit | changed

- name: Create snaps storage folder
  file:
    state: directory
    path: "{{ consul_snapshot_storage }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0744
