---
# PostgreSQL-related settings
postgresql_is_local: "{{ 'true' if project_db_host | search( 'localhost|127\\.0\\.0\\.1|^/') else 'false' }}"
application_dbuser_role_attr_flags:
buffer_memory: '{{ quarter_system_memory | default("128MB") }}'
