---
mysql_root_home: /root
mysql_root_username: "root"
mysql_root_password: "{{ vault_maria_mysql_root_password | default('change_this') }}"

dss_db:
  user: "{{ dss_db_user }}"
  password: "{{ dss_db_password | default('change_this') }}"
  name: "{{ dss_db_name }}"

mysql_users:
  - name: "{{ dss_db.user | default('dss_user') }}"
    host: "%"
    password: "{{ dss_db.password }}"
    priv: "{{ dss_db.name }}.*:ALL"

mysql_databases:
  - name: "{{ dss_db.name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
