---
- name: install building software and build essentials
  apt:
    name: ['python-setuptools','acl','build-essential','wget','git','curl','apt-transport-https']
    state: present
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes

- name: update python's crypto libs
  pip:
    name: ['urllib3', 'pyopenssl', 'ndg-httpsclient', 'pyasn1']
