---
- name: Install startup script for workers
  template: "src=plum-derivatives.service dest=/etc/systemd/system/{{plum_worker_name}}.service"
  notify: Restart plum workers
- name: Keep workers running
  service: "name={{plum_worker_name}} enabled=yes state=started"
- name: Allow deploy user to restart workers
  lineinfile: "dest=/etc/sudoers state=present line='{{deploy_user}} ALL=(ALL) NOPASSWD: /usr/sbin/service {{plum_worker_name}} {{item}}' validate='visudo -cf %s'"
  with_items:
    - status
    - restart
    - start
- name: Update PATH because /etc/environment does not work with systemd
  lineinfile: >
              dest='/home/{{deploy_user}}/.bashrc'
              state=present
              regexp='^PATH=$PATH:/opt/fits:/opt/kakadu$'
              line="PATH=$PATH:/opt/fits:/opt/kakadu"
              insertbefore=BOF
- name: Install local nameserver
  apt: name={{item}} state=installed
  with_items:
    - bind9
  become: true
- name: Start nameserver
  service: "name=bind9 enabled=yes state=started"
- name: Remove other nameservers
  lineinfile: dest=/etc/resolv.conf state=absent regexp='.*nameserver.*'
- name: Use local nameserver
  lineinfile: dest=/etc/resolv.conf state=present line='nameserver 127.0.0.1'
