---
discoveryutils_docroot: '/var/www/discoveryutils'
discoverutils_git_repo: 'https://github.com/pulibrary/discoveryutils.git'
discovery_utils_version_branch: 'master'
dependencies:
  - { role: pulibrary.drupal }
  - { role: pulibrary.solr }
  - { role: pulibrary.redis }
