---
- name: create scripts directory
  file:
    path: /home/{{ deploy_user }}/scripts
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    state: directory
- name: copy shell script that restarts plum-worker
  copy:
    src: plum_worker.sh
    dest: /home/{{ deploy_user }}/scripts/plum_worker.sh
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "a+x"
- name: Install startup script for workers
  template: "src=plum-worker.conf dest=/lib/systemd/system/{{plum_worker_name}}s.service"
  notify: Restart plum workers
- name: Keep workers running
  service: "name={{plum_worker_name}}s enabled=yes state=started"
- name: Allow deploy user to restart workers
  lineinfile: "dest=/etc/sudoers state=present line='{{deploy_user}} ALL=(ALL) NOPASSWD: /bin/systemdctl {{item}} {{plum_worker_name}}s' validate='visudo -cf %s'"
  with_items:
    - status
    - restart
    - start
