---
- name: Install dependencies
  apt:
    name: '{{item}}'
    state: present
  with_items:
    - libpq-dev
    - libsqlite3-dev

- name: Update ruby gems
  command: gem update --system
  become: yes
  become_method: sudo

- name: Install site configuration
  template:
    src: 'pulmap_config'
    dest: '/home/{{deploy_user}}/app_configs'
    owner: '{{deploy_user}}'
    group: '{{deploy_user}}'

- name: Install startup script for workers
  template:
    src: 'pulmap-sneakers.service'
    dest: '/etc/systemd/system/pulmap-sneakers.service'
  notify: Restart pulmap workers

- name: Keep workers running
  service:
    name: 'pulmap-sneakers'
    enabled: yes
    state: started

- name: Allow deploy user to restart workers
  lineinfile:
    dest: '/etc/sudoers'
    state: present
    line: '{{deploy_user}} ALL=(ALL) NOPASSWD: /usr/sbin/service pulmap-sneakers {{item}}'
    validate: 'visudo -cf %s'
  with_items:
    - status
    - restart
    - start
