---
- name: install redis
  apt: 
    name: redis-server
    state: present
    update_cache: yes
  when: ansible_distribution_release == "xenial"

- name: install redis
  apt:
    name: redis
    state: present
  when: ansible_distribution_release == "bionic"

- name: configure redis
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: make sure redis starts on boot
  service:
    name: redis-server
    enabled: yes
