---
- name: Check if database server is installed
  environment:
    LC_MESSAGES: 'C'
  shell: dpkg-query -W -f='${Version}\n' 'mariadb-server' | grep -v '^$'
  register: mariadb__register_version
  changed_when: false
  failed_when: false
  check_mode: false

- name: add mariadb repo keys
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "0xF1656F24C74CD1D8"

- name: add maria db repository
  apt_repository:
    repo: "deb [arch=amd64,ppc64el] https://mirrors.evowise.com/mariadb/repo/10.3/ubuntu {{ ansible_distribution_release }} main"

- name: Install database client packages
  apt:
    name: ["python-mysqldb", "mysql-client"]
    state: present
    install_recommends: false
