---
- name: add mariadb repo keys
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "0xF1656F24C74CD1D8"

- name: remove maria db repository for client installation
  apt_repository:
    repo: "deb [arch=amd64,i386,ppc64el] https://mirrors.evowise.com/mariadb/repo/10.2/ubuntu {{ ansible_distribution_release }} main"
    state: absent

- name: add maria db 10.3 repository
  apt_repository:
    repo: "deb [arch=amd64,ppc64el] https://mirrors.evowise.com/mariadb/repo/10.3/ubuntu {{ ansible_distribution_release }} main"

- name: install mariadb client dev headers
  apt:
    name: ["libmariadbclient-dev-compat"]
    state: present
    update_cache: true

- name: MySQL | Ensure MySQL users are present.
  mysql_user:
    name: "{{ item.name }}"
    login_host: "{{ maria_db_cluster_host }}"
    login_password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_username }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
  with_items: "{{ mysql_users }}"

- name: MySQL | Ensure MySQL databases are present.
  mysql_db:
    login_host: "{{ maria_db_cluster_host }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items: "{{ mysql_databases }}"
  register: dss__register_database
