---
- name: add mariadb repo keys
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "0xF1656F24C74CD1D8"

- name: remove maria db repository for client installation
  apt_repository:
    repo: "deb [arch=amd64,i386,ppc64el] https://mirrors.evowise.com/mariadb/repo/10.2/ubuntu {{ ansible_distribution_release }} main"
    state: absent

- name: add maria db 10.3 repository
  apt_repository:
    repo: "deb [arch=amd64,ppc64el] https://mirrors.evowise.com/mariadb/repo/10.3/ubuntu {{ ansible_distribution_release }} main"

- name: install mariadb client dev headers
  apt:
    name: ["libmariadbclient-dev-compat"]
    state: present
    update_cache: true

- name: create mysql user
  mysql_user:
    login_host: '{{ db_host }}'
    login_user: 'root'
    login_password: '{{ mariadb_server__root_password }}'
    name: '{{ dss_db_user }}'
    password: '{{ dss_db_password }}'
    state: present
    priv: '{{ dss_db_name }}.*:ALL'

- name: create mysql database
  mysql_db:
    name: '{{ dss_db_name }}'
    encoding: 'utf8'
    login_host: '{{ db_host }}'
    login_password: '{{ dss_db_password }}'
    login_user: '{{ dss_db_user }}'
