---
- name: generate config search user secret
  shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 32"
  register: search_user_secret
- name: generate config public user secret
  shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 32"
  register: public_user_secret
- name: generate config staff user secret
  shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 32"
  register: staff_user_secret
- name: generate front end user secret
  shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 64"
  register: frontend_cookie_secret
- name: generate public cookie secret
  shell: "cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 64"
  register: public_cookie_secret
