---
- include: setup_mysql.yml
- include: generate_secrets.yml

- set_fact:
    url_jdbc_archivesspace: '{{ url_jdbc_base }}{{ archivesspace_db_name }}?user={{ archivesspace_db_user }}&password={{ archivesspace_db_password }}{{ url_jdbc_suffix }}'

- name: we need unzip for the next step
  apt:
    name: unzip
    state: present

- name: unzip archivesspace into opt dir
  unarchive:
    src: 'https://github.com/archivesspace/archivesspace/releases/download/{{ archivesspace_version }}/archivesspace-{{ archivesspace_version }}.zip'
    dest: /opt
    creates: '/opt/archivesspace/archivesspace.sh'
    remote_src: True
    owner: '{{ archivesspace_db_user }}'
    group: '{{ archivesspace_db_user }}'

- name: download  mysql connector in place
  get_url:
    url: https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.42/mysql-connector-java-5.1.42.jar
    dest: '/opt/archivesspace/lib/'
    checksum: md5:803783e5c40c911c92d4b6b5ea324912
    force: no

- name: config db access
  template: src=config.rb.j2 dest=/opt/archivesspace/config/config.rb

- name: setup database
  shell: chdir=/opt/archivesspace/ ./scripts/setup-database.sh

- name: delete indexed_state files which force re-index
  shell: rm -f /opt/archivesspace/data/indexer_state/*
