---
# handlers file for roles/pulibrary.patroni
- name: restart patroni-watchdog
  systemd:
    name: patroni-watchdog
    state: restarted
    daemon_reload: true
    enabled: true
  notify:
    - restart watchdog

- name: restart watchdog
  systemd:
    name: watchdog
    state: restarted
    enabled: true

- name: restart patroni
  systemd:
    name: patroni.service
    state: restarted
    daemon_reload: true
    enabled: true
