---
- name: install application packages
  apt:
    name: '{{ item }}'
    state: present
  loop:
    - 'zookeeper'
    - 'zookeeperd'

- name: Remove if available upstart service
  file:
    path: '/etc/init.d/zookeeper'
    state: absent

- name: create systemd service
  template:
    src: 'zookeeper.service.j2'
    dest: '/lib/systemd/system/zookeeper.service'
  notify:
    - Restart zookeeper

- name: Ensure that Zookeeper is running
  service: "name=zookeeper enabled=yes state=started"
