---
galaxy_info:
  role_name: pulibrary.consul
  author: pulibrary
  description: Role to set up Hashicorp's Consul
  company: Princeton University Library

  license: MIT

  min_ansible_version: 2.4.0.0

  platforms:
    - name: Ubuntu
      versions:
        - 16.04
        - 18.04

dependencies:
  - role: 'pulibrary.common'
