---

- name: Install the Gearman job server
  apt:
    name: gearman-job-server
    state: present

- name: Install service script for AtoM workers
  template:
    src: atom-worker.service
    dest: /etc/systemd/system/atom-worker.service

- name: Keep AtoM worker running
  service:
    name: atom-worker.service
    enabled: true
    state: started
